apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
    - name: hello-world
      image: docker.io/library/busybox
      command: ["/bin/sh", "-c"]
      args: ["echo Hello, World! && sleep 3600"]
